### ISSUE TITLE
there is an extra * character in line 78 in plots.py script

### ISSUE THREAD

**Issue by Abolfazl-Alipour** [KaliLab/ca3net#1]
the code was not able to plot the results from "spw_network.py" and the issue was the extra * in line 78 in plots.py script,
this might need to be changed.
    fig_name = os.path.join(fig_dir, "%.2f*.png"%multiplier_)
change to
    fig_name = os.path.join(fig_dir, "%.2f.png"%multiplier_)

**Comment by andrisecker** [comment]
@Abolfazl-Alipour that multiplication sign is within the string (`"...*..."`) so it shouldn't cause any problems as far as I know (and it ran smoothly for us so far) but I've got rid of it anyway.

**Comment by Abolfazl-Alipour** [comment]
I see. Thanks for the quick feedback!
